.\" Copyright © 2023 TTKB, LLC.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS”
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.Dd $Mdocdate$
.Dt DEDUP 1
.Os
.Sh NAME
.Nm dedup
.Nd replace duplicate file data with a copy-on-write clone.
.Sh SYNOPSIS
.Nm dedup
.Op Fl PVnvx
.Op Fl t threads
.Op Fl d depth
.Op Ar
.Sh DESCRIPTION
.Nm
finds files with identical content using the provided
.Ar
argument(s). Duplicates are replaced with a clone of another (using
.Xr clonefile 2
). If no
.Ar
is specified, the current directory is used.
.Pp
Cloned files share data blocks with the file they were cloned from, saving space
on disk. Unlike a hard linked file, any future modification to either the clone
or the original file will be remain private to that file (copy-on-write).
.Pp
.Nm
works in two phases. First it evaluates all of the paths provided
recursively, looking for duplicates. Once all duplicates are found, any files
that are not already clones of "best" clone source are replaced with clones.
.Pp
There are limits which files can be cloned:
.Bl -enum -offset indent
.It
the file must be a regular file
.It
the file must have only one hard link
.It
the file and its directory must be writable by the user
.El
.Pp
The "best" source is chosen by first finding the file with the most hard links.
Files with multiple hard links will not be replaced, so using them as the source
of other clones allows their blocks to be shared without modifying the data to
which they point. If all files have a single link, a file which shares the most
clones with others is chosen. This ensures that files which have been previously
processed will not need to be replaced during subsequent evaluations of the same
directory. If none of the files have multiple links or clones, the first file
encountered will be chosen.
.Pp
Files with multiple hard links are not replaced because it is not possible to
guarantee all other links to that inode exist within the tree(s) being
evaluated. Replacing a link with a clone changes the semantics from two link
pointing at the same, mutable shared storage to two links pointing at the same
copy-on-write storage. For scenarios where hard links were previously being
used because clones were not available, future versions may provide a flag to
destructively replace hard links with clones. Future versions may also consider
cloning files with multiple hard links if all links are within the space being
evaluated and two or more hard link clusters reference duplicated data.
.Pp
Finally, if all matched files are transparently HFS compressed, none of the
files will be replaced because of how HFS compressed files are stored in the
file system. These files have no data blocks, so cloning them does not provide
any benefit.
.Pp
.Nm
will only work on volumes that have the
.Ar VOL_CAP_INT_CLONE
capability. Currently that is limited to APFS.
.Pp
While
.Nm
is primarily intended to be used to save storage by using clones, it also
provides
.Fl l
and
.Fl s
flags to replace duplicates with hard links or symbolic links respectively. Care
should be taken when using these options, however. Unlike clones, the replaced
files share the metadata of one of the matched files, though it might not seem
deterministic which one. If these options are used with automation where all
files have default ownership and permissions, there should be little issue. The
created files are also not copy-on-write and will share any modifications made.
These options should only be used if the consequences of each choice are
understood.
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl d Ar depth , Fl Fl depth Ar depth
Only traverse
.Ar depth
directories deep into each provided path.
.It Fl h
Display sizes using SI suffixes with 2-4 digits of precision.
.It Fl n , Fl Fl dry-run
Evaluate all files and find all duplicates but only print what would be done
and do not modify any files.
.It Fl l , Fl Fl link
Replace duplicate files with hard links instead of clones. Replaced files will
not retain their metadata.
.It Fl s , Fl Fl symlink
Replace duplicate files with symbolic links instead of clones. Replaced files
will not retain their metadata.
.It Fl P , Fl Fl no-progress
Do not display a progress bar.
.It Fl t Ar threads
The number of threads to use for evaluating files. By default this is the same
as the number of CPUs on the host as described by the
.Ar hw.ncpu
value returned by
.Xr sysctl 8 .
If the value 0 is provided all evaluation will be done serially in the main
thread.
.It Fl V , Fl Fl version
Print the version and exit
.It Fl v , Fl Fl verbose
Increase verbosity. May be specified multiple times.
.It Fl x , Fl Fl one-file-system
Prevent
.Nm
from descending into directories that have a device number different than that
of the file from which the descent began.
.It Fl ? , Fl Fl help
Print a summary of options and exit.
.El
.\" .Sh ENVIRONMENT
.\" If the environment variables
.\" .Ev CLICOLOR
.\" or
.\" .Ev COLORTERM
.\" are set while running in an interactive terminal,
.\" .Tn ANSI
.\" color sequences will be used.
.\" .Sh FILES
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success and >0 if an error occurs.
.Pp
It is possible that during abnormal termination a temporary clone will be left
before it is moved to the path it is replacing. In such cases a file with the
prefix .~. followed by the name of the file that was to be replaced will exist
in the same directory as target file.
.Pp
.Xr find 1
can be used to find these temporary files if necessary.
.Pp
.Dl $ find . -name '.~.*'
.Sh EXAMPLES
Find all duplicates and display which files would be replaced by clones along
with the estimated space that would be saved:
.Pp
.Dl $ dedup -n
.Pp
Limit execution to a single thread, disable progress, and display human readable
output while deduplicating files in `~/Downloads` and `/tmp`
.Pp
.Dl $ dedup -t1 -Ph ~/Downloads /tmp
.Pp
When creating archive files that support hard links it may be beneficial to use the
.Fl l
option to reduce the archive size.
.Pp
.Dl $ dedup -l build
.Sh SEE ALSO
.Xr clonefile 2 ,
.Xr copyfile 3 ,
.Xr link 2 ,
.Xr symlink 2
.Sh STANDARDS
Sometimes.
.\" .Sh HISTORY
.Sh AUTHORS
.Nm
was written by
.An Jonathan Hohle Aq Mt jon@ttkb.co .
.\" .Sh CAVEATS
.\" .Sh BUGS
.Sh SECURITY CONSIDERATIONS
.Nm
makes a best effort attempt to replace original files with clones that have
the same permissions, metadata, and ACLs. Support for copying metadata comes
from
.Xr copyfile 3
.
