name: CI

on:
  push:
    branches-ignore: [ "master" ]
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v
    - name: make check
      run: make check
